---
name: Java CI with Gradle
"on":
  push:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitignore
    - .gitattributes
    - LICENSE
    - '**/*.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - .editorconfig
    - .gitignore
    - .gitattributes
    - LICENSE
    - '**/*.md'
jobs:
  build:
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: |
          17
          25
        distribution: temurin
        cache: gradle
    - name: Clean
      run: gradle clean
    - name: Build
      run: gradle classes testClasses
    - name: Test
      run: gradle test
    - name: Lint
      run: gradle lint
    - name: Publishing
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      run: gradle publish
    - name: DeepSource
      env:
        DEEPSOURCE_DSN: "${{ secrets.DEEPSOURCE_DSN }}"
      run: |
        curl https://deepsource.com/cli | sh
        ./bin/deepsource report --analyzer test-coverage --key java --value-file ./build/reports/jacoco/test/jacocoTestReport.xml
